version: '3.4'

services:
  todoapi:
    image: todoapp
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - 5000:80
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: postgres:latest
    container_name: 'postgres_container'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ada
      - POSTGRES_DB=todo
    ports: 
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

